# Generated by Django 2.0.1 on 2018-11-26 20:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('actions', '0007_manualuserpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='owner',
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_backer',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
