# Generated by Django 2.0.1 on 2019-03-06 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0010_userquery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlistened',
            name='action',
        ),
        migrations.DeleteModel(
            name='UserListened',
        ),
    ]
