# Generated by Django 2.0.1 on 2019-05-06 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0013_actiongeneric'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actiongeneric',
            name='to_user',
            field=models.ForeignKey(help_text='The user that will see this act/action', on_delete=django.db.models.deletion.DO_NOTHING, related_name='generic_actions', to=settings.AUTH_USER_MODEL),
        ),
    ]
