# Generated by Django 2.0.1 on 2018-03-26 20:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('alexa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AUserEmotionalState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('attribute', model_utils.fields.StatusField(choices=[('happiness', 'happiness'), ('anxiety', 'anxiety'), ('delusional', 'delusional'), ('loneliness', 'loneliness')], db_index=True, default='happiness', max_length=100, no_check_for_status=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='emotional_states', to='alexa.AUser')),
            ],
            options={
                'db_table': 'a_user_emotional_state',
                'ordering': ('-created',),
            },
        ),
    ]
