# Generated by Django 2.0.1 on 2018-03-26 22:23

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('alexa', '0002_auseremotionalstate'),
    ]

    operations = [
        migrations.CreateModel(
            name='AUserMedicalState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('measurement', model_utils.fields.StatusField(choices=[('blood_pressure', 'blood_pressure')], db_index=True, default='blood_pressure', max_length=100, no_check_for_status=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='medical_state', to='alexa.AUser')),
            ],
            options={
                'db_table': 'a_user_medical_state',
            },
        ),
    ]
