# Generated by Django 2.0.1 on 2018-04-03 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alexa', '0003_ausermedicalstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='auser',
            name='engine_schedule',
            field=models.TextField(blank=True, default=''),
        ),
    ]
