# Generated by Django 2.0.1 on 2018-05-09 23:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alexa', '0004_auto_20180508_2325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='circlemembership',
            name='is_person_of_interest',
        ),
        migrations.AddField(
            model_name='circle',
            name='person_of_interest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='main_circle', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='circlemembership',
            name='circle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='circle', to='alexa.Circle'),
        ),
        migrations.AlterField(
            model_name='circlemembership',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='circle_memberships', to=settings.AUTH_USER_MODEL),
        ),
    ]
