# Generated by Django 2.0.1 on 2018-04-10 08:11

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alexa', '0004_auser_engine_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='auser',
            name='profile',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
