# Generated by Django 2.0.1 on 2018-05-09 23:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alexa', '0005_auto_20180509_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circle',
            name='person_of_interest',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='main_circle', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
