# Generated by Django 2.0.1 on 2018-05-09 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alexa', '0006_auto_20180509_2335'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='circlemembership',
            unique_together={('circle', 'member')},
        ),
    ]
