# Generated by Django 2.0.1 on 2018-05-16 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actstream', '0002_remove_action_data'),
        ('alexa', '0010_auto_20180514_2252'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelationalAction',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('actstream.action',),
        ),
    ]
