# Generated by Django 2.0.1 on 2018-05-24 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alexa', '0011_relationalaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='like',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='like',
            name='owner',
        ),
        migrations.DeleteModel(
            name='RelationalAction',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
