# Generated by Django 2.0.1 on 2018-06-07 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alexa', '0013_auto_20180529_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.TextField(blank=True, default=''),
        ),
    ]
