# Generated by Django 2.0.1 on 2018-06-19 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alexa', '0015_news'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='main',
            new_name='content',
        ),
    ]
