# Generated by Django 2.0.1 on 2018-06-20 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alexa', '0016_auto_20180619_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractoncontent',
            name='object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_actions_on_content', to='alexa.News'),
        ),
    ]
