# Generated by Django 2.0.1 on 2018-06-20 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('alexa', '0018_auto_20180620_0233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractoncontent',
            name='object',
        ),
        migrations.AddField(
            model_name='useractoncontent',
            name='content_type',
            field=models.ForeignKey(default=16, on_delete=django.db.models.deletion.DO_NOTHING, to='contenttypes.ContentType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useractoncontent',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
