# Generated by Django 2.0.1 on 2018-07-05 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alexa', '0020_auto_20180703_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='enginesession',
            name='ttl',
            field=models.PositiveIntegerField(default=600),
        ),
    ]
