# Generated by Django 2.0.1 on 2018-07-18 21:17

import alexa.mixins
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('alexa', '0021_enginesession_ttl'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('song_name', models.TextField()),
                ('song_location', models.TextField()),
            ],
            options={
                'db_table': 'song',
            },
            bases=(models.Model, alexa.mixins.FetchRandomMixin),
        ),
    ]
