# Generated by Django 2.0.1 on 2018-07-17 06:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('alexa', '0021_enginesession_ttl'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('entry_text', models.TextField()),
                ('fact_list', jsonfield.fields.JSONField(default=[])),
                ('ending_yes_no_question', models.TextField()),
            ],
            options={
                'db_table': 'fact',
            },
        ),
        migrations.CreateModel(
            name='FactType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.TextField(db_index=True)),
            ],
            options={
                'db_table': 'fact_type',
            },
        ),
        migrations.AddField(
            model_name='fact',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='facts', to='alexa.FactType'),
        ),
    ]
