# Generated by Django 2.0.1 on 2018-07-17 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alexa', '0022_auto_20180717_0600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractoncontent',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='useractoncontent',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
