# Generated by Django 2.0.1 on 2018-07-19 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alexa', '0022_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song_owner',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
