# Generated by Django 2.0.1 on 2018-07-20 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alexa', '0024_auto_20180720_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='genre',
            field=models.TextField(default='classical'),
            preserve_default=False,
        ),
    ]
