# Generated by Django 2.0.1 on 2018-07-21 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alexa', '0023_auto_20180717_2000'),
        ('alexa', '0025_song_genre'),
    ]

    operations = [
    ]
