# Generated by Django 2.0.1 on 2018-07-24 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alexa', '0026_merge_20180721_0100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auser',
            old_name='alexa_id',
            new_name='alexa_user_id',
        ),
        migrations.AddField(
            model_name='auser',
            name='alexa_device_id',
            field=models.TextField(db_index=True, default='amzn1.ask.device.AERMGPRS6JFPJREAHBTMB6PBP5KGPV2OP2TZBL5UEXCTQCYN72IRZNWIG27LI4HT52DB3LZO6IY7HFQOMYCATBZ7U5UXCUPJO4RYNGPZGHMVNHIQWOCLVIF4TJOFWRSFTFZQR5XAYF3KNSQREU2F6WIFQL2EFAI7XRWU3RTYSJQNHMQVXTI5O', editable=False),
            preserve_default=False,
        ),
    ]
