# Generated by Django 2.0.1 on 2018-07-31 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alexa', '0027_auto_20180725_0457'),
        ('alexa', '0027_auto_20180724_1730'),
    ]

    operations = [
    ]
