# Generated by Django 2.0.1 on 2018-08-05 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alexa', '0029_auto_20180801_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auser',
            name='alexa_device_id',
            field=models.TextField(editable=False),
        ),
        migrations.AddIndex(
            model_name='auser',
            index=models.Index(fields=['alexa_device_id', 'alexa_user_id'], name='a_user_alexa_d_46dd6a_idx'),
        ),
    ]
