# Generated by Django 2.0.1 on 2018-09-14 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alexa', '0031_user_is_anonymous_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.TextField(default='unknown'),
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.TextField(default='unknown'),
        ),
    ]
