# Generated by Django 2.0.1 on 2019-01-14 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('senior_living_facility', '0001_initial'),
        ('alexa', '0032_auto_20180914_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='senior_living_facility',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='senior_living_facility.SeniorLivingFacility'),
        ),
    ]
