# Generated by Django 2.0.1 on 2019-01-19 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0010_voicemessagestatus'),
        ('alexa', '0034_auto_20190115_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hardware',
            field=models.ForeignKey(default=None, help_text="The hardware in senior's room", null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='streaming.HardwareRegistry'),
        ),
        migrations.AddField(
            model_name='user',
            name='room_no',
            field=models.CharField(blank=True, default='', help_text='The room number of the senior. It is only meaningful for the senior', max_length=8, verbose_name='Room Number'),
        ),
    ]
