# Generated by Django 2.0.1 on 2019-01-22 21:38

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('alexa', '0036_familyprospect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familyprospect',
            name='email',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='familyprospect',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default=None, max_length=128, null=True),
        ),
    ]
