# Generated by Django 2.0.1 on 2019-03-03 01:09

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('alexa', '0043_usersettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='data',
            field=jsonfield.fields.JSONField(default={'genres': []}),
        ),
    ]
