# Generated by Django 2.0.1 on 2019-03-07 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('alexa', '0044_auto_20190302_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='CircleInvitation',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('name', models.TextField(null=True)),
                ('surname', models.TextField(null=True)),
                ('invitation_code', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('circle', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='alexa.Circle')),
                ('converted_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_user_from_invitation', to=settings.AUTH_USER_MODEL)),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='circle_inviter', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'circle_invitation',
            },
        ),
        migrations.CreateModel(
            name='CircleReinvitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('circle_invitation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='alexa.CircleInvitation')),
            ],
            options={
                'db_table': 'circle_reinvitation',
            },
        ),
    ]
