# Generated by Django 2.0.1 on 2019-03-29 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alexa', '0045_circleinvitation_circlereinvitation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fact',
            name='fact_type',
        ),
        migrations.DeleteModel(
            name='News',
        ),
        migrations.DeleteModel(
            name='Song',
        ),
        migrations.DeleteModel(
            name='Fact',
        ),
        migrations.DeleteModel(
            name='FactType',
        ),
    ]
