# Generated by Django 2.0.1 on 2019-03-07 02:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('alexa', '0045_circleinvitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='CircleReinvitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('circle_invitation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='alexa.CircleInvitation')),
            ],
            options={
                'db_table': 'circle_reinvitation',
            },
        ),
    ]
