# Generated by Django 2.0.1 on 2019-04-26 19:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('alexa', '0047_auto_20190425_2310'), ('alexa', '0048_auto_20190425_2317'), ('alexa', '0049_auto_20190426_1201')]

    dependencies = [
        ('alexa', '0046_auto_20190329_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_anonymous_user',
        ),
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Birthday'),
        ),
        migrations.AddField(
            model_name='user',
            name='caregivers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'user_type': 'CAREGIVER'}, related_name='in_care_circle_of', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='move_in_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Move In Date'),
        ),
        migrations.AddField(
            model_name='user',
            name='service_type',
            field=models.TextField(blank=True, choices=[('INDEPENDENT', 'Independent'), ('ASSISTED', 'Assisted')], default=''),
        ),
    ]
