# Generated by Django 2.0.1 on 2019-01-14 22:37

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeniorLivingFacility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=160)),
                ('facility_id', models.CharField(default='', help_text='text identifier specifying location, too: e.g. CA.Fremont.Brookdale', max_length=200, unique=True)),
                ('calendar_url', models.URLField(blank=True, default=None, null=True)),
                ('timezone', models.CharField(default='America/Los_Angeles', max_length=200)),
            ],
            options={
                'verbose_name': 'Senior Living Facility',
                'verbose_name_plural': 'Senior Living Facilities',
                'db_table': 'senior_living_facility',
            },
        ),
    ]
