# Generated by Django 2.0.1 on 2018-10-16 21:31

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SeniorLivingFacility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=160)),
                ('facility_id', models.CharField(default='', help_text='text identifier specifying location, too: e.g. CA.Fremont.Brookdale', max_length=200, unique=True)),
                ('calendar', models.TextField(blank=True, default='')),
                ('residents', models.ManyToManyField(related_name='senior_living_facilities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Senior Living Facility',
                'verbose_name_plural': 'Senior Living Facilities',
                'db_table': 'senior_living_facility',
            },
        ),
    ]
