# Generated by Django 2.0.1 on 2018-11-14 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senior_living_facility', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seniorlivingfacility',
            name='timezone',
            field=models.CharField(default='America/Los_Angeles', max_length=200),
        ),
    ]
