# Generated by Django 2.0.1 on 2018-11-16 05:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('senior_living_facility', '0003_auto_20181114_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeniorActOnFacilityContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('act', model_utils.fields.StatusField(choices=[('Heard', 'Heard'), ('RSVP:Yes', 'RSVP:Yes')], default=None, max_length=100, no_check_for_status=True)),
            ],
            options={
                'verbose_name': "Senior' Act On Facility Content",
                'verbose_name_plural': "Seniors' Acts On Facility Content",
                'db_table': 'senior_act_on_facility_content',
            },
        ),
        migrations.CreateModel(
            name='SeniorLivingFacilityContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('text_content', models.TextField(blank=True, default='')),
                ('text_content_hash', models.TextField(blank=True, db_index=True, default='')),
                ('audio_url', models.URLField(blank=True, default='')),
                ('senior_living_facility', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='senior_living_facility.SeniorLivingFacility')),
            ],
            options={
                'db_table': 'senior_living_facility_content',
            },
        ),
        migrations.AddField(
            model_name='senioractonfacilitycontent',
            name='content',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='senior_living_facility.SeniorLivingFacilityContent'),
        ),
        migrations.AddField(
            model_name='senioractonfacilitycontent',
            name='senior',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterIndexTogether(
            name='seniorlivingfacilitycontent',
            index_together={('senior_living_facility', 'text_content')},
        ),
    ]
