# Generated by Django 2.0.1 on 2019-02-27 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senior_living_facility', '0003_auto_20190208_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='seniorlivingfacility',
            name='check_in_deadline',
            field=models.TimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='seniorlivingfacility',
            name='check_in_reminder',
            field=models.TimeField(default=None, null=True),
        ),
    ]
