# Generated by Django 2.0.1 on 2019-02-28 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senior_living_facility', '0004_auto_20190227_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='seniorlivingfacility',
            name='check_in_morning_start',
            field=models.TimeField(default=None, null=True),
        ),
    ]
