# Generated by Django 2.0.1 on 2018-11-16 05:38

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('senior_living_facility', '0004_auto_20181115_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='seniorlivingfacilitycontent',
            name='content_type',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='Daily-Calendar-Summary', max_length=100, no_check_for_status=True),
        ),
        migrations.AlterIndexTogether(
            name='seniorlivingfacilitycontent',
            index_together={('senior_living_facility', 'text_content', 'content_type')},
        ),
    ]
