# Generated by Django 2.0.1 on 2019-03-06 01:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('senior_living_facility', '0005_seniorlivingfacility_check_in_morning_start'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeniorDeviceUserActivityLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('activity', models.TextField(db_index=True)),
                ('data', jsonfield.fields.JSONField(default={})),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='device_user_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Senior Device User Activity Log',
                'verbose_name_plural': 'Senior Device User Activity Logs',
                'db_table': 'senior_device_user_activity_log',
            },
        ),
        migrations.AlterField(
            model_name='seniorlivingfacility',
            name='check_in_morning_start',
            field=models.TimeField(default='05:30:00', null=True),
        ),
    ]
