# Generated by Django 2.0.1 on 2019-03-12 10:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('senior_living_facility', '0006_auto_20190305_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeniorLivingFacilityContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('content_type', model_utils.fields.StatusField(choices=[('Daily-Calendar-Summary', 'Daily-Calendar-Summary'), ('Event', 'Event'), ('Check-In-Call', 'Check-In-Call')], default='Daily-Calendar-Summary', max_length=100, no_check_for_status=True)),
                ('text_content', models.TextField(blank=True, default='')),
                ('text_content_hash', models.TextField(blank=True, db_index=True, default='')),
                ('audio_url', models.URLField(blank=True, default='')),
                ('senior_living_facility', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='senior_living_facility.SeniorLivingFacility')),
            ],
            options={
                'db_table': 'senior_living_facility_content',
            },
        ),
        migrations.AlterField(
            model_name='seniordeviceuseractivitylog',
            name='created',
            field=model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AlterIndexTogether(
            name='seniorlivingfacilitycontent',
            index_together={('senior_living_facility', 'text_content', 'content_type')},
        ),
    ]
