# Generated by Django 2.0.1 on 2019-03-12 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senior_living_facility', '0007_auto_20190312_0326'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='seniorlivingfacilitycontent',
            index_together=set(),
        ),
        migrations.AddIndex(
            model_name='seniorlivingfacilitycontent',
            index=models.Index(fields=['senior_living_facility', 'text_content', 'content_type'], name='senior_livi_senior__d81870_idx'),
        ),
    ]
