# Generated by Django 2.0.1 on 2019-03-12 23:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('senior_living_facility', '0008_auto_20190312_1146'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeniorLivingFacilityMessageLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('content_type', models.TextField(choices=[('call-for-morning-check-in', 'Call for Morning Check In'), ('custom-message', 'Custom Message')], default=None)),
                ('medium_type', models.TextField(choices=[('text', 'Text'), ('voice', 'Voice')], default=None)),
                ('delivery_type', models.TextField(choices=[('urgent-mail', 'Urgent Mail'), ('voice-mail', 'Voice Mail')], default=None)),
                ('data', jsonfield.fields.JSONField(default={})),
                ('senior_living_facility', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='senior_living_facility.SeniorLivingFacility')),
            ],
            options={
                'db_table': 'senior_living_facility_message_log',
            },
        ),
        migrations.RemoveField(
            model_name='seniordeviceuseractivitylog',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='seniorlivingfacilitycontent',
            name='modified',
        ),
    ]
