# Generated by Django 2.0.1 on 2019-03-12 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senior_living_facility', '0009_auto_20190312_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seniorlivingfacility',
            name='check_in_deadline',
            field=models.TimeField(default='10:00:00'),
        ),
        migrations.AlterField(
            model_name='seniorlivingfacility',
            name='check_in_morning_start',
            field=models.TimeField(default='05:30:00'),
        ),
    ]
