# Generated by Django 2.0.1 on 2019-03-23 08:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('senior_living_facility', '0010_auto_20190312_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentDeliveryRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(default=django.utils.timezone.now)),
                ('end', models.DateTimeField()),
                ('frequency', models.IntegerField(default=0, help_text='Frequency in seconds. If the field is set to 0 it means that it is for one time use')),
            ],
            options={
                'db_table': 'content_delivery_rule',
            },
        ),
        migrations.AlterField(
            model_name='seniorlivingfacilitycontent',
            name='content_type',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='Daily-Calendar', max_length=100, no_check_for_status=True),
        ),
        migrations.AddIndex(
            model_name='contentdeliveryrule',
            index=models.Index(fields=['start', 'end', 'frequency'], name='content_del_start_d0e9cf_idx'),
        ),
        migrations.AddField(
            model_name='seniorlivingfacilitycontent',
            name='delivery_rule',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='senior_living_facility.ContentDeliveryRule'),
        ),
    ]
