# Generated by Django 2.0.1 on 2019-03-23 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('senior_living_facility', '0011_auto_20190323_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seniorlivingfacilitycontent',
            name='delivery_rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='senior_living_facility.ContentDeliveryRule'),
        ),
    ]
