# Generated by Django 2.0.1 on 2019-03-27 00:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields
import model_utils.fields
import utilities.views.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('alexa', '0045_circleinvitation_circlereinvitation'),
        ('senior_living_facility', '0011_auto_20190324_0128'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeniorLivingFacilityMockUserData',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('checkin_status', models.TextField(choices=[('NOTIFIED', 'Notified'), ('PENDING', 'Pending'), ('STAFF_CHECKED', 'Staff Checked'), ('SELF_CHECKED', 'Self Checked')], default='PENDING')),
                ('senior', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('checkin_info', jsonfield.fields.JSONField(default={})),
                ('device_status', jsonfield.fields.JSONField(default={})),
            ],
            options={
                'db_table': 'mock_user_data',
            },
        ),
    ]
