# Generated by Django 2.0.1 on 2019-03-27 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('senior_living_facility', '0013_seniorlivingfacilitymockmessagedata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seniorlivingfacilitymockmessagedata',
            name='senior',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
