# Generated by Django 2.0.1 on 2019-03-28 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('senior_living_facility', '0015_auto_20190327_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mockmessagethread',
            name='senior',
        ),
        migrations.DeleteModel(
            name='MockMessageThread',
        ),
    ]
