# Generated by Django 2.0.1 on 2019-04-02 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senior_living_facility', '0016_auto_20190327_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='seniorlivingfacility',
            name='profile_pic',
            field=models.TextField(blank=True, default=''),
        ),
    ]
