# Generated by Django 2.0.1 on 2019-03-28 08:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('senior_living_facility', '0016_auto_20190327_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('receiver', models.ForeignKey(help_text='The facility that is in charge of fulfilling the service request', on_delete=django.db.models.deletion.DO_NOTHING, to='senior_living_facility.SeniorLivingFacility')),
                ('requester', models.ForeignKey(help_text='The user who requested the service (i.e. pressed the request button on the hardware)', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'service_request',
            },
        ),
    ]
