# Generated by Django 2.0.1 on 2019-04-02 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('senior_living_facility', '0017_seniorlivingfacility_profile_pic'),
        ('senior_living_facility', '0017_servicerequest'),
    ]

    operations = [
    ]
