# Generated by Django 2.0.1 on 2019-04-04 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('senior_living_facility', '0018_merge_20190402_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('content', models.TextField(help_text='Content which will be processed with text to speech.', null=True)),
                ('content_audio_file', models.TextField(help_text='This field will be populated either from an voice record audio url or text to speech process.', null=True)),
                ('delivery_rule', models.TextField(choices=[('injectable', 'injectable'), ('voice-mail', 'voice-mail'), ('urgent-mail', 'urgent-mail')], default='injectable')),
                ('is_response_expected', models.BooleanField(default=False)),
                ('message_source_user', models.ForeignKey(help_text='The user who sent the message.', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'message',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='MessageResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('response', models.NullBooleanField(default=None, help_text='Message response True represents Yes, False Represents No, Null represents No Reply')),
                ('from_user', models.ForeignKey(help_text='User who responses the message', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('message', models.ForeignKey(help_text='Response Requested Message', on_delete=django.db.models.deletion.DO_NOTHING, to='senior_living_facility.Message')),
            ],
            options={
                'db_table': 'message_response',
            },
        ),
        migrations.CreateModel(
            name='MessageThread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
            ],
            options={
                'db_table': 'message_thread',
            },
        ),
        migrations.CreateModel(
            name='MessageThreadParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('is_all_receipients', models.BooleanField(default=False, help_text='If true user field needs to be empty')),
                ('message_thread', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='senior_living_facility.MessageThread')),
                ('senior_living_facility', models.ForeignKey(help_text='Message thread participating senior living facility', on_delete=django.db.models.deletion.DO_NOTHING, to='senior_living_facility.SeniorLivingFacility')),
                ('user', models.ForeignKey(help_text='Message thread participating user', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'message_thread_participant',
            },
        ),
        migrations.AddField(
            model_name='message',
            name='message_thread',
            field=models.ForeignKey(help_text='Collection of messages between related participants.', on_delete=django.db.models.deletion.DO_NOTHING, to='senior_living_facility.MessageThread'),
        ),
        migrations.AlterUniqueTogether(
            name='messagethreadparticipant',
            unique_together={('user', 'senior_living_facility')},
        ),
    ]
