# Generated by Django 2.0.1 on 2019-04-05 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('senior_living_facility', '0019_auto_20190404_0144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='message_source_user',
            new_name='source_user',
        ),
        migrations.RenameField(
            model_name='messagethreadparticipant',
            old_name='is_all_receipients',
            new_name='is_all_recipients',
        ),
        migrations.AlterField(
            model_name='message',
            name='delivery_rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='senior_living_facility.ContentDeliveryRule'),
        ),
    ]
