# Generated by Django 2.0.1 on 2019-04-06 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('senior_living_facility', '0020_auto_20190405_0238'),
        ('senior_living_facility', '0018_auto_20190402_1537'),
    ]

    operations = [
    ]
