# Generated by Django 2.0.1 on 2019-04-13 02:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('senior_living_facility', '0021_merge_20190406_0233'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityCheckInOperationForSenior',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('date', models.DateField(help_text='Check in information date for senior.')),
                ('notified', models.DateField(default=None, null=True)),
                ('checked', models.DateField(default=None, null=True)),
                ('senior', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='facility_check_in_operations', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(help_text='The facility staff that made the check in', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'facility_check_in_operation_for_senior',
            },
        ),
        migrations.AddIndex(
            model_name='facilitycheckinoperationforsenior',
            index=models.Index(fields=['senior', 'date'], name='facility_ch_senior__1e7339_idx'),
        ),
    ]
