# Generated by Django 2.0.1 on 2019-04-17 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('senior_living_facility', '0023_auto_20190412_1930'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagethreadparticipant',
            options={'ordering': ['-created']},
        ),
    ]
