# Generated by Django 2.0.1 on 2019-04-25 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('senior_living_facility', '0024_auto_20190417_0419'),
        ('senior_living_facility', '0024_auto_20190423_1713'),
    ]

    operations = [
    ]
