# Generated by Django 2.0.1 on 2019-05-11 00:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('senior_living_facility', '0025_merge_20190424_2118'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureFlagCommunityApp',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('senior_living_facility', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='senior_living_facility.SeniorLivingFacility')),
                ('morning_check_in', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'feature_flag_community_app',
            },
        ),
    ]
