# Generated by Django 2.0.1 on 2019-05-14 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('senior_living_facility', '0026_seniorlivingfacilityfeatureflags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seniorlivingfacilitymockmessagedata',
            name='senior',
        ),
        migrations.RemoveField(
            model_name='seniorlivingfacilitymockuserdata',
            name='senior',
        ),
        migrations.DeleteModel(
            name='SeniorLivingFacilityMockMessageData',
        ),
        migrations.DeleteModel(
            name='SeniorLivingFacilityMockUserData',
        ),
    ]
