# Generated by Django 2.0.1 on 2019-05-19 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0029_auto_20190519_0314'),
        ('senior_living_facility', '0027_auto_20190514_0609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='content_audio_file',
        ),
        migrations.AddField(
            model_name='message',
            name='audio_file',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='streaming.AudioFile'),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True, default='', help_text='Content which will be processed with text to speech.'),
        ),
    ]
