# Generated by Django 2.0.1 on 2019-05-23 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senior_living_facility', '0030_seniorlivingfacility_zip_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='seniorlivingfacilitycontent',
            name='ssml_content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
