# Generated by Django 2.0.1 on 2018-03-19 22:27

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('task_list', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SomeState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', django_fsm.FSMField(choices=[('draft', 'draft'), ('approved', 'approved'), ('published', 'published'), ('removed', 'removed')], default='draft', max_length=50, protected=True, verbose_name='Publication State')),
                ('can_display', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'some_state',
            },
        ),
    ]
