# Generated by Django 2.0.1 on 2018-03-20 17:18

from django.db import migrations
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('task_list', '0002_somestate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alexasession',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
    ]
