# Generated by Django 2.0.1 on 2018-03-20 17:30

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_list', '0003_auto_20180320_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='alexarequestlog',
            name='done_time',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='alexarequestlog',
            name='state',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='alexauser',
            name='state',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'engines': {}, 'unfinished_tasks': {}}),
        ),
    ]
