# Generated by Django 2.0.1 on 2018-03-21 01:22

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('task_list', '0004_auto_20180320_1730'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlexaRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('request', django.contrib.postgres.fields.jsonb.JSONField()),
                ('engine', models.TextField(default=None, null=True)),
                ('state', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('done_time', models.DateTimeField(default=None, null=True)),
            ],
            options={
                'db_table': 'alexa_request',
            },
        ),
        migrations.RemoveField(
            model_name='alexarequestlog',
            name='session',
        ),
        migrations.AlterField(
            model_name='alexaenginelog',
            name='created',
            field=model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='alexaenginelog',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='alexasession',
            name='created',
            field=model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='alexasession',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.DeleteModel(
            name='AlexaRequestLog',
        ),
        migrations.AddField(
            model_name='alexarequest',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alexa_requests', to='task_list.AlexaSession'),
        ),
    ]
