# Generated by Django 2.0.1 on 2018-04-14 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_list', '0005_auto_20180321_0122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alexaenginelog',
            name='alexa_user',
        ),
        migrations.RemoveField(
            model_name='alexarequest',
            name='session',
        ),
        migrations.RemoveField(
            model_name='alexasession',
            name='alexa_user',
        ),
        migrations.RemoveField(
            model_name='alexauser',
            name='user',
        ),
        migrations.DeleteModel(
            name='AlexaEngineLog',
        ),
        migrations.DeleteModel(
            name='AlexaRequest',
        ),
        migrations.DeleteModel(
            name='AlexaSession',
        ),
        migrations.DeleteModel(
            name='AlexaUser',
        ),
    ]
