# Generated by Django 2.0.1 on 2018-04-14 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_list', '0006_auto_20180414_1930'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SomeState',
        ),
    ]
