# Generated by Django 2.0.1 on 2018-04-20 17:22

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('task_list', '0007_delete_somestate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(db_index=True, default=None, max_length=128, null=True),
        ),
    ]
