# Generated by Django 2.0.1 on 2018-04-20 17:26

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('task_list', '0008_auto_20180420_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, db_index=True, default='', max_length=128),
            preserve_default=False,
        ),
    ]
