# Generated by Django 2.0.1 on 2019-05-23 21:37

from django.db import migrations, models
import django.utils.timezone
import jsonfield.fields
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfoWeather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('zip_code', models.CharField(db_index=True, max_length=5)),
                ('is_call_successful', models.BooleanField(default=False)),
                ('raw_data', jsonfield.fields.JSONField(default=dict)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('temperature_current', models.IntegerField()),
                ('temperature_min', models.IntegerField()),
                ('temperature_max', models.IntegerField()),
                ('comment', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'info_weather',
            },
        ),
    ]
