HC_USER_ID = 2
HC_CIRCLE_ID = 1
HC_MSG_SOURCE_USER_ID = 2
HC_MSG_DESTINATION_USER_ID = 1
HC_FAMILY_MEMBER_FIRST_NAME = 'John'
HC_PUSHER_CHANNEL = 'family.senior.1'
HC_HARDWARE_USER_DEVICE_ID_PREFIX = 'hw-user'