# Generated by Django 2.0.1 on 2018-08-11 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofile',
            name='url',
            field=models.TextField(db_index=True, help_text='File URL, it must be publicly accessible'),
        ),
    ]
