# Generated by Django 2.0.1 on 2018-08-15 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0003_hardwareregistry_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofile',
            name='name',
            field=models.TextField(db_index=True, help_text='For internal use only'),
        ),
    ]
