# Generated by Django 2.0.1 on 2018-08-16 00:22

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0004_auto_20180814_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='cache',
            field=jsonfield.fields.JSONField(default={}),
        ),
    ]
