# Generated by Django 2.0.1 on 2018-08-20 22:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0005_playlist_cache'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlisthasaudio',
            name='play_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playlisthasaudio',
            name='play_time',
            field=models.TextField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening'), ('daylong', 'Daylong')], default='daylong'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Who is it for?', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
