# Generated by Django 2.0.1 on 2018-08-30 06:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid
from streaming.models import AudioFile

audio_file = AudioFile.objects.all()[0]


def create_uuid(apps, schema_editor):
    PlaylistHasAudio = apps.get_model('streaming', 'PlaylistHasAudio')
    for pha in PlaylistHasAudio.objects.all():
        pha.hash = uuid.uuid4()
        pha.save(update_fields=['hash'])


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0008_auto_20180829_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlisthasaudio',
            name='hash',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.RunPython(create_uuid),
        migrations.AddField(
            model_name='userplayliststatus',
            name='current_active_audio',
            field=models.ForeignKey(default=str(audio_file.id), on_delete=django.db.models.deletion.DO_NOTHING, to='streaming.AudioFile'),
            preserve_default=False,
        ),
    ]
