# Generated by Django 2.0.1 on 2018-10-16 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0008_auto_20180904_1446'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audiofile',
            options={'verbose_name_plural': 'Audio Files'},
        ),
        migrations.AlterModelOptions(
            name='hardwareregistry',
            options={'verbose_name_plural': 'Hardware Registries'},
        ),
        migrations.AlterModelOptions(
            name='playlisthasaudio',
            options={'ordering': ['order_id'], 'verbose_name_plural': 'Playlist Has Audios'},
        ),
    ]
