# Generated by Django 2.0.1 on 2018-10-01 18:08

from django.db import migrations, models
import django.utils.timezone
import jsonfield.fields
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0008_auto_20180904_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('message', jsonfield.fields.JSONField(default={})),
                ('process_state', models.CharField(choices=[('queued', 'Queued'), ('complete', 'Complete'), ('failed', 'Failed'), ('running', 'Running')], default='queued', max_length=50)),
            ],
            options={
                'db_table': 'message_queue',
            },
        ),
        migrations.AlterModelOptions(
            name='audiofile',
            options={'verbose_name_plural': 'Audio Files'},
        ),
        migrations.AlterModelOptions(
            name='hardwareregistry',
            options={'verbose_name_plural': 'Hardware Registries'},
        ),
        migrations.AlterModelOptions(
            name='playlisthasaudio',
            options={'ordering': ['order_id'], 'verbose_name_plural': 'Playlist Has Audios'},
        ),
    ]
