# Generated by Django 2.0.1 on 2019-02-08 09:15

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0010_voicemessagestatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='created',
            field=model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='process_state',
            field=models.CharField(choices=[('queued', 'Queued'), ('complete', 'Complete'), ('failed', 'Failed'), ('running', 'Running')], db_index=True, default='queued', max_length=50),
        ),
    ]
