# Generated by Django 2.0.1 on 2018-12-27 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0009_auto_20181016_1410'),
        ('streaming', '0010_voicemessagestatus'),
    ]

    operations = [
    ]
