# Generated by Django 2.0.1 on 2019-02-12 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alexa', '0041_auto_20190212_0909'),
        ('streaming', '0011_auto_20190208_0115'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HardwareRegistry',
        ),
        migrations.RemoveField(
            model_name='trackingaction',
            name='session',
        ),
        migrations.RemoveField(
            model_name='trackingaction',
            name='user',
        ),
        migrations.DeleteModel(
            name='TrackingAction',
        ),
    ]
