# Generated by Django 2.0.1 on 2019-02-22 00:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0012_auto_20190212_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voicemessagestatus',
            name='destination',
            field=models.ForeignKey(help_text='Voice Destination User (None means facility-wide message)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='voice_destination_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
