# Generated by Django 2.0.1 on 2019-03-02 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0013_auto_20190221_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='is_setting_available',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
