# Generated by Django 2.0.1 on 2019-03-03 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0014_tag_is_setting_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='label',
            field=models.TextField(default='A', help_text="Label is the text that is readable by the users. Tags are exposed as settings for end user if `is_setting_available` set for the tag. An example for label is 'Classical Music' for classical songs, where name may be 'song-classical'."),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tag',
            name='is_setting_available',
            field=models.BooleanField(help_text='This makes the tag available as settings on the family mobile app.'),
        ),
    ]
