# Generated by Django 2.0.1 on 2019-03-19 23:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('alexa', '0045_circleinvitation_circlereinvitation'),
        ('streaming', '0015_auto_20190302_1830'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserContentRepository',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='content_repository', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('injected_content_repository', jsonfield.fields.JSONField(default=[])),
            ],
            options={
                'db_table': 'user_content_repository',
            },
        ),
    ]
