# Generated by Django 2.0.1 on 2019-03-23 08:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0016_usercontentrepository'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercontentrepository',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
