# Generated by Django 2.0.1 on 2019-03-25 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0017_auto_20190323_0105'),
        ('streaming', '0017_auto_20190321_1951'),
    ]

    operations = [
    ]
