# Generated by Django 2.0.1 on 2019-03-26 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0018_merge_20190325_0652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.TextField(help_text="Name is how server use the tags. This is used for backend processes. Use '-' (dash) instead of spaces and all lower case. E.g. 'song-jazz'"),
        ),
    ]
