# Generated by Django 2.0.1 on 2019-03-27 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0019_auto_20190325_1741'),
        ('streaming', '0019_auto_20190326_1501'),
    ]

    operations = [
    ]
