# Generated by Django 2.0.1 on 2019-03-29 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0020_merge_20190327_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofile',
            name='audio_type',
            field=models.CharField(choices=[('song', 'Song'), ('podcast', 'Podcast'), ('joke', 'Joke'), ('family_update', 'Family Update'), ('miscellaneous', 'Miscellaneous')], max_length=50),
        ),
    ]
