# Generated by Django 2.0.1 on 2019-04-01 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0022_song'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voicemessagestatus',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='voicemessagestatus',
            name='source',
        ),
        migrations.AlterField(
            model_name='audiofile',
            name='audio_type',
            field=models.CharField(choices=[('song', 'Song'), ('family_update', 'Family Update'), ('miscellaneous', 'Miscellaneous')], max_length=50),
        ),
        migrations.AlterField(
            model_name='audiofile',
            name='url',
            field=models.URLField(db_index=True, help_text='File URL, it must be publicly accessible'),
        ),
        migrations.DeleteModel(
            name='VoiceMessageStatus',
        ),
    ]
