# Generated by Django 2.0.1 on 2019-04-02 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0024_auto_20190401_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofile',
            name='audio_type',
            field=models.CharField(choices=[('song', 'Song'), ('facility-auto-generated-content', 'Facility Auto Generated Content'), ('family_update', 'Family Update'), ('miscellaneous', 'Miscellaneous')], max_length=50),
        ),
    ]
