# Generated by Django 2.0.1 on 2019-04-04 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('streaming', '0026_audiofile_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAudioFileSignal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('signal', models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative')], default='positive', max_length=50)),
                ('audio_file', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='liked_by_users', to='streaming.AudioFile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='liked_audio_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_audio_file_signal',
            },
        ),
    ]
