# Generated by Django 2.0.1 on 2019-04-06 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0024_auto_20190404_0144'),
        ('streaming', '0027_useraudiofilesignal'),
    ]

    operations = [
    ]
