# Generated by Django 2.0.1 on 2019-05-19 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0028_merge_20190406_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofile',
            name='audio_type',
            field=models.CharField(choices=[('song', 'Song'), ('facility-auto-generated-content', 'Facility Auto Generated Content'), ('facility-message', 'Facility Message'), ('family_update', 'Family Update'), ('miscellaneous', 'Miscellaneous')], max_length=50),
        ),
    ]
